/*
PROGRAMMER: 	CEZAR ALGIU
CSU ID:		***
ASSIGNMENT NO:	3
CLASS:		CIS620
DATE:		12/04/2016
/*


/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bank.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <strings.h>
#include <string.h>
#include <termios.h>
#include <time.h>
#include <sys/select.h>
#include <fcntl.h>
#include <sys/file.h>
#include <asm-generic/errno-base.h>
#include <assert.h>
#include <linux/if_packet.h>
#include <sys/ioctl.h>
#include <unistd.h>


void
create_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	trans  create_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CREATE_PROG, CREATE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

///////////////
        int id;
        printf("Enter desired account id to be added:");
        fflush(stdout);
        fflush(stdin);
//get id from the keyboard
        scanf("%d",&id);
//assign that id to the struct
	create_1_arg.id = id;
//send the struct
	result_1 = create_1(&create_1_arg, clnt);
	if (result_1 == (int *) NULL)
	{
		clnt_perror (clnt, "call failed");
	}

	else
	{
		if(*result_1 == -1)	printf("Account already exists\n");
		else			printf("Account added!\n");
	}
/////////////////

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

//////////////////////////////
//////////////////////////////

void
add_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	trans  add_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

///////////////







        int id;
	int amount;
        printf("Enter id:");
        fflush(stdout);
        fflush(stdin);
        scanf("%d",&id);

        printf("Enter amount:");
        fflush(stdout);
        fflush(stdin);
        scanf("%d",&amount);


        add_1_arg.id = id;
	add_1_arg.amount = amount;

        result_1 = add_1(&add_1_arg, clnt);
        if (result_1 == (int *) NULL) {
                clnt_perror (clnt, "call failed");
        }

        else
        {
                if(*result_1 == -1)      printf("Account does not exist\n");
		else if(*result_1 == -2) printf("Can't add this! Wrong amount\n");
                else if(*result_1 == 1 ) printf("Money added!\n");
		else			 printf("Something is not right here\n");
        }

/////////////////





#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

///////////////////////////////////
///////////////////////////////////

void
withdraw_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	trans  withdraw_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, WITHDRAW_PROG, WITHDRAW_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

        int id;
        int amount;
        printf("Enter id:");
        fflush(stdout);
        fflush(stdin);
        scanf("%d",&id);

        printf("Enter amount to be withdrawn:");
        fflush(stdout);
        fflush(stdin);
        scanf("%d",&amount);


        withdraw_1_arg.id = id;
        withdraw_1_arg.amount = amount;

        result_1 = withdraw_1(&withdraw_1_arg, clnt);
        if (result_1 == (int *) NULL) {
                clnt_perror (clnt, "call failed");
        }

        else
        {
                if(*result_1 == -1)      printf("Account does not exist\n");
                else if(*result_1 == -2) printf("Can't withdraw this! Wrong amount\n");
                else if(*result_1 == -3) printf("Insuficient funds!\n");
                else if(*result_1 == 1 ) printf("Money withdrawn!\n");
                else                     printf("Something is not right here\n");
        }

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

/////////////////////////////////
/////////////////////////////////

void
inquiry_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	trans  inquiry_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, INQUIRY_PROG, INQUIRY_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */


	int id;
        printf("Enter desired account id to be inquired:");
        fflush(stdout);
        fflush(stdin);
        scanf("%d",&id);

        inquiry_1_arg.id = id;

        result_1 = inquiry_1(&inquiry_1_arg, clnt);
        if (result_1 == (int *) NULL) {
                clnt_perror (clnt, "call failed");
        }


        else
        {
                if(*result_1 == -1)     printf("Account does not exist!\n");
                else                    printf("Account inquiry:%d\n",*result_1);
        }

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

///////////////////////////////
///////////////////////////////

int
main (int argc, char *argv[])
{
	char *host;
	FILE *tty = fopen("/dev/tty","r");
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	char option[10];//=malloc(sizeof(char));
	while(1)
	{

		fprintf(stdout,"\n Enter the command number and hit enter: \n");
                fprintf(stdout,"\n 1 -Create account id \n");
                fprintf(stdout,"\n 2 -Add money to account \n");
                fprintf(stdout,"\n 3 -Remove money from account \n");
                fprintf(stdout,"\n 4 -Account Inquiry \n");
		fprintf(stdout,"\n 9 -EXIT \n->");

		fflush(stdout);
		fflush(stdin);
		fgets(option,sizeof(option),tty);
                option[strlen(option) - 1] = '\0';

		//HERE ARE THE OPRIONS AND THE RPC FUNCTION CALLING

                if(strlen(option)>1) printf("Hey the input is wrong");

		else if (option[0] == '1')
		{
			create_prog_1 (host);
		}

                else if (option[0] == '2')
                {
                	add_prog_1 (host);
                }

                else if (option[0] == '3')
                {
                        withdraw_prog_1 (host);
                }

                else if (option[0] == '4')
                {
                        inquiry_prog_1 (host);
                }

                else if (option[0] == '9')
                {
                        fclose(tty);
			exit(0);
                }

		else
		{
			printf("Bad input!");
		}

	}

//	exit (0);
}
