/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BANK_H_RPCGEN
#define _BANK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct trans {
	int id;
	int amount;
};
typedef struct trans trans;

#define CREATE_PROG 4211
#define CREATE_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CREATE 1
extern  int * create_1(trans *, CLIENT *);
extern  int * create_1_svc(trans *, struct svc_req *);
extern int create_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CREATE 1
extern  int * create_1();
extern  int * create_1_svc();
extern int create_prog_1_freeresult ();
#endif /* K&R C */

#define ADD_PROG 4212
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  int * add_1(trans *, CLIENT *);
extern  int * add_1_svc(trans *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  int * add_1();
extern  int * add_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

#define WITHDRAW_PROG 4213
#define WITHDRAW_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define WITHDRAW 1
extern  int * withdraw_1(trans *, CLIENT *);
extern  int * withdraw_1_svc(trans *, struct svc_req *);
extern int withdraw_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define WITHDRAW 1
extern  int * withdraw_1();
extern  int * withdraw_1_svc();
extern int withdraw_prog_1_freeresult ();
#endif /* K&R C */

#define INQUIRY_PROG 4214
#define INQUIRY_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INQUIRY 1
extern  int * inquiry_1(trans *, CLIENT *);
extern  int * inquiry_1_svc(trans *, struct svc_req *);
extern int inquiry_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INQUIRY 1
extern  int * inquiry_1();
extern  int * inquiry_1_svc();
extern int inquiry_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_trans (XDR *, trans*);

#else /* K&R C */
extern bool_t xdr_trans ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BANK_H_RPCGEN */
